### ISSUE TITLE
Identify proper way to implement GLP3+ license

### ISSUE THREAD

**Issue by luisponti** [casasglobal-org/casas-gis#115]
Current implementation comes from here:
https://spdx.org/licenses/GPL-3.0-or-later.html

(depends on #117)

**Comment by neteler** [comment]
We could also add SPDX License IDs to the file headers, like:

```
...
* SPDX-License-Identifier: GPL-3.0-or-later
...
```

**Comment by luisponti** [comment]
That's sounds super smart! I need to look into it. On reviewing the SPDX page again, I have spotted a place where it says how to modify GPL3 to make it GPL3+

We still need to figure out how to deal with the `COPYING` file:
<https://github.com/casasglobal-org/casas-gis/blob/main/COPYING>

Need to recover another link you provided for including contributions as authors. Do you recall that @neteler ? 

I was wondering if we could/should add my email (`quartese gmail.com`) to the header of scripts where only my name is present, such as in Perl scripts. Those scrips also also missing a copyright line for CASAS.

**Comment by luisponti** [comment]
Found it! This is the citation suggestion you made, @neteler 

> Maybe one [license] file is enough, the authors could be moved into AUTHORS.md? Or even better: CITATION.cff [1]?

> [1] If you need support here, this: https://github.com/citation-file-format/cffconvert and ChatGPT are very helpful

**Comment by luisponti** [comment]
### The way it is right now:

The reason both a LICENSE and COPYING file were added is because I thought the way to get GPL3+ was to have the GPL3 LICENSE file plus a COPYING file stating that you could use GPL3 or any later version:

> This program is free software: you can redistribute it and/or modify it under
> the terms of the GNU General Public License as published by the Free Software
> Foundation, either version 3 of the License, **or (at your option) any later
> version.**

My idea was to do something similar to GRASS, where there is both a license and a copying file:
https://github.com/OSGeo/grass/blob/main/GPL.TXT
https://github.com/OSGeo/grass/blob/main/COPYING

The copyright statement (i.e., the COPYING file) was modeled using instructions found at this link:
https://spdx.org/licenses/GPL-3.0-or-later.html

The other two CASAS public repos that I set up also have a similar LICENSE and COPYING files, see:
https://github.com/casasglobal-org/casas-gis
https://github.com/casasglobal-org/casas-pbdm

This is just to provide background as to why things are the way they are right now.

**Comment by neteler** [comment]
In the case of GRASS GIS, the way of license declaration come from the efforts in 1999 and around.

## Headers

The **copyright** notice shall stay untouched.

**License** declaration:

- The plan in GRASS GIS is to revisit the headers using the SPDX entry and simplify the declaration, see https://github.com/OSGeo/grass/issues/4190
- GDAL has picked up this idea and already implemented the simplification, see https://github.com/OSGeo/gdal/issues/10903
  - Even Rouault has written the script `spdxify.py` for this task, see https://github.com/OSGeo/gdal/pull/10910

## Files

https://www.gnu.org/licenses/gpl-howto.en.html
Citation: _In GNU programs we conventionally put the license in a file called COPYING._

IANAL: In the GRASS GIS case, probably these files could be somehow merged (not an issue for CASAS):
- https://github.com/OSGeo/grass/blob/main/GPL.TXT
- https://github.com/OSGeo/grass/blob/main/COPYING

GDAL has collated all licenses into a single file: https://github.com/OSGeo/gdal/blob/master/LICENSE.TXT
